// create shift constants
export const CREATE_SHIFT_REQUEST = "CREATE_SHIFT_REQUEST";
export const CREATE_SHIFT_SUCCESS = "CREATE_SHIFT_SUCCESS";
export const CREATE_SHIFT_FAIL = "CREATE_SHIFT_FAIL";

// get all shifts constants
export const GET_SHIFTS_REQUEST = "GET_SHIFTS_REQUEST";
export const GET_SHIFTS_SUCCESS = "GET_SHIFTS_SUCCESS";
export const GET_SHIFTS_FAIL = "GET_SHIFTS_FAIL";

// get shifts by day constants
export const GET_SHIFTS_BY_DAY_REQUEST = "GET_SHIFTS_BY_DAY_REQUEST";
export const GET_SHIFTS_BY_DAY_SUCCESS = "GET_SHIFTS_BY_DAY_SUCCESS";
export const GET_SHIFTS_BY_DAY_FAIL = "GET_SHIFTS_BY_DAY_FAIL";

// get shifts by day constants
export const SET_CURRENT_SHIFT_REQUEST = "SET_CURRENT_SHIFT_REQUEST";
export const SET_CURRENT_SHIFT_SUCCESS = "SET_CURRENT_SHIFT_SUCCESS";
export const SET_CURRENT_SHIFT_FAIL = "SET_CURRENT_SHIFT_FAIL";
